<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-01T19:43:55 IST" name="Suite" finished-at="2024-12-01T19:45:00 IST" duration-ms="65245">
    <groups>
    </groups>
    <test started-at="2024-12-01T19:43:55 IST" name="Test" finished-at="2024-12-01T19:45:00 IST" duration-ms="65245">
      <class name="tests.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.LoginTest@41a0aa7d]" started-at="2024-12-01T19:43:56 IST" name="setUp" finished-at="2024-12-01T19:44:03 IST" duration-ms="7691" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testValidLogin()[pri:1, instance:tests.LoginTest@41a0aa7d]" started-at="2024-12-01T19:44:03 IST" name="testValidLogin" finished-at="2024-12-01T19:44:03 IST" duration-ms="12" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test case Failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test case Failed
at org.testng.Assert.fail(Assert.java:111)
at tests.LoginTest.testValidLogin(LoginTest.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:569)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidLogin -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:tests.LoginTest@41a0aa7d]" started-at="2024-12-01T19:44:03 IST" name="TearDown" finished-at="2024-12-01T19:44:04 IST" duration-ms="224" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
        <test-method signature="testInvalidLogin()[pri:2, instance:tests.LoginTest@41a0aa7d]" started-at="2024-12-01T19:44:04 IST" name="testInvalidLogin" finished-at="2024-12-01T19:44:04 IST" depends-on-methods="tests.LoginTest.testValidLogin" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method tests.LoginTest.testInvalidLogin() on instance tests.LoginTest@41a0aa7d depends on not successfully finished methods 
[tests.LoginTest.testValidLogin() on instance tests.LoginTest@41a0aa7d]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method tests.LoginTest.testInvalidLogin() on instance tests.LoginTest@41a0aa7d depends on not successfully finished methods 
[tests.LoginTest.testValidLogin() on instance tests.LoginTest@41a0aa7d]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidLogin -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.LoginTest@41a0aa7d]" started-at="2024-12-01T19:44:04 IST" name="setUp" finished-at="2024-12-01T19:44:08 IST" duration-ms="4359" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="SelectProductandCheckout()[pri:3, instance:tests.LoginTest@41a0aa7d]" started-at="2024-12-01T19:44:08 IST" name="SelectProductandCheckout" finished-at="2024-12-01T19:45:00 IST" duration-ms="51794" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SelectProductandCheckout -->
        <test-method is-config="true" signature="TearDown()[pri:0, instance:tests.LoginTest@41a0aa7d]" started-at="2024-12-01T19:45:00 IST" name="TearDown" finished-at="2024-12-01T19:45:00 IST" duration-ms="378" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- tests.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
